language: "python"
cache: "pip"
python:
  - "2.7"
  - "3.5"
env:
  global:  # 'travis encrypt PYPI_PASSWORD=... GH_TOKEN=...'
    - PYPI_USERNAME=honzajavorek
    - secure: "fjvWMrCuRVznTg72qSofo6kDpVGnXKqOl/80Yt+J3gNUuMw1PnjE/PUkmVPjfYQWNEWaiu3pEb9DaqG4ZD3DQZZIb0GCF/geIKmZYaRE2sIaAMoSbwMjhxEabVHtWJoMfldN/qtz09beGRvWcywz/WcPnWCCxBhkWojfNhN7hrQ="
install:
  - "pip install -e .[tests,release]"
script:
  - "pylama"
  - "pytest --cov-report="
after_success:
  - "coveralls"
  - "python setup.py publish"
