[tool.poetry]
name = "fiobank"
version = "4.0.0"
description = "Fio Bank API in Python (unofficial)"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "ICS"
readme = "README.rst"
repository = "https://github.com/honzajavorek/fiobank"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
responses = "^0.22.0"
mock = "^5.0.1"

[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = "env venv .git"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
