name: Release

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build and inspect package
        uses: hynek/build-and-inspect-python-package@v2

  smoke-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built package
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: dist

      - uses: astral-sh/setup-uv@v7

      - name: Smoke Test
        run: |
          uv venv .smoketest
          uv pip install --python=.smoketest/bin/python ./dist/fiobank-*.tar.gz
          .smoketest/bin/python -c 'from fiobank import FioBank'
          rm -r .smoketest

  publish:
    needs: smoke-test
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'honzajavorek/fiobank'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fiobank
    permissions:
      id-token: write
    steps:
      - name: Download built package
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: dist

      - uses: astral-sh/setup-uv@v7

      - name: Publish package
        run: uv publish --trusted-publishing always
